### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by hectorprats** [misteio/CloudinaryBundle#1]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/symfony v2.6.11
    - Conclusion: don't install symfony/symfony v2.6.11
    - Conclusion: don't install symfony/symfony v2.6.10
    - Conclusion: don't install symfony/symfony v2.6.9
    - Conclusion: don't install symfony/symfony v2.6.8
    - Conclusion: don't install symfony/symfony v2.6.7
    - Conclusion: don't install symfony/symfony v2.6.6
    - Conclusion: don't install symfony/symfony v2.6.5
    - Conclusion: don't install symfony/symfony v2.6.4
    - Conclusion: don't install symfony/symfony v2.6.3
    - Installation request for misteio/cloudinary-bundle dev-master -> satisfiable by misteio/cloudinary-bundle[dev-master].
    - Conclusion: don't install symfony/symfony v2.6.2
    - Conclusion: don't install symfony/symfony v2.6.1
    - misteio/cloudinary-bundle dev-master requires symfony/finder ~2.7 -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.2, v2.7.3].
    - don't install symfony/finder v2.7.0|don't install symfony/symfony v2.6.0
    - don't install symfony/finder v2.7.1|don't install symfony/symfony v2.6.0
    - don't install symfony/finder v2.7.2|don't install symfony/symfony v2.6.0
    - don't install symfony/finder v2.7.3|don't install symfony/symfony v2.6.0
    - Installation request for symfony/symfony 2.6.\* -> satisfiable by symfony/symfony[v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9].

What can I do?

**Comment by misteio** [comment]
What is your version of Symfony ? You need 2.7.\* and it seems you have 2.6.\* installed.
