### ISSUE TITLE
Bundle d'ont work with video

### ISSUE THREAD

**Issue by fyher** [misteio/CloudinaryBundle#2]
it's possible to upload a video ?

**Comment by misteio** [comment]
I will look this feature !

**Comment by fyher** [comment]
for upload the video i have write this in CloudinaryWrapper 

` public function uploadvideo($source,$param){

```
    $this->uploadedResult = $this->getUploader()->upload_large($source, $param);
    return $this;

}`
```

but i don't arrive to write the code to see the video in twig :(

**Comment by misteio** [comment]
Sorry for the delay, but now it's done.
