### ISSUE TITLE
cloudinary_php version 1.6.2

### ISSUE THREAD

**Issue by hvalcourtSerdy** [misteio/CloudinaryBundle#3]
Hi, 

I would like to know why your bundle use cloudinary/cloudinary_php": "1.4.2", and not the last  version 1.6.2.

Is there a problem after 1.4.2 ?

cloudinary_php
https://github.com/cloudinary/cloudinary_php/blob/master/composer.json

Thanks for the work

**Comment by misteio** [comment]
Hi ! 

Sorry for the delay, I updated to the latest version, 1.7.1

Have a good day.

**Comment by hvalcourtSerdy** [comment]
Thanks a lot ! :-)
