### ISSUE TITLE
cloudinary folder parameter

### ISSUE THREAD

**Issue by hvalcourtSerdy** [misteio/CloudinaryBundle#4]
Hi,
is it possible to add more Cloudinary options to upload function in CloudinaryWrapper ?

http://cloudinary.com/documentation/upload_images

instead of : 
`public function upload($source, $publicId, $tags = array())`

you could have something like :
`public function upload($source, $publicId, $tags = array(), options = array())`

Can be usefull to use the folder parameter (or other options) 
```
\Cloudinary\Uploader::upload("sample.jpg", 
    array("folder" => "my_folder/my_sub_folder/", "public_id" => "my_name"));
```

Thanks for the work,

Hugo

**Comment by misteio** [comment]
Yes, I'ts updated. Now you can use an $option in  upload Method.

Thanks for your avice :).

**Comment by hvalcourtSerdy** [comment]
Thanks a lot ! :-)
