### ISSUE TITLE
upload_large not available in wrapper

### ISSUE THREAD

**Issue by tousignantf** [misteio/CloudinaryBundle#5]
Hello,

in order to upload large files in chunks, it would be useful to wrap the upload_large() method that is available in the Cloudinary uploader.

For now, I had to modify the uploadVideo method of the wrapper to invoke Uploader::upload_large instead of Uploader::upload, which is not a suitable solution.

Thanks :-)

**Comment by misteio** [comment]
Hey !

I added this with a boolean option on upload_video. I updated the doc.

Have a good day.

**Comment by tousignantf** [comment]
Merci :-)
