### ISSUE TITLE
Get an image with HTTPS

### ISSUE THREAD

**Issue by AndoniLarz** [misteio/CloudinaryBundle#6]
Hello,

I'm using the bundle in my project and I recently set up HTTPS, but the pages where I use this bundle to display images from cloudinary are not fully HTTPS because the Twig filter gives an HTTP url.

Is it possible to fetch an image forcing the HTTPS protocol ?

**Comment by misteio** [comment]
Hello!
Good question. I will try to add an option for https.
I think this will be done in few days.

**Comment by misteio** [comment]
For using HTTPS, you can pass an option secure like this : 'secure'=>true

In twig : 	$cloudinary -> show('public_name', array('width' => 150, 'height' => 150,  'secure'=>true));

**Comment by AndoniLarz** [comment]
Great, thank you !
